### ISSUE TITLE
Wrong colors when using sync-inoreader

### ISSUE THREAD

**Issue by ewancoder** [themoken/canto-curses#25]
Latest clean (without configs) version of canto-curses-git is running fine (blue colors). But if you add latest version of sync-inoreader.py and configure username/password, canto-curses fills your screen with errors and colors are just bad. I have no time to track this at the moment, so I'll just leave it there.

[Canto logs](https://gist.github.com/ewancoder/9c865d1e7ba7611a1b52)

It was present in some version ago, so it's not the most recent issue. I just had no time to compose an issue and used inoreader in web.

**Comment by themoken** [comment]
Hey Ewan, I just pushed a commit to fix the improper validation of the colors, but I think your core issue is the ERROR in the daemon log parsing the config, which is that there are two (or more) feeds with the same name ("Canto"). I think the real bug is that that the daemon didn't properly kill itself with the bad config.

Did sync-inoreader add that redefinition? Does it work right when you remove it?

**Comment by ewancoder** [comment]
Well, I updated canto, removed .canto-ng, added inoreader plugin and started it again - all the errors were still present. But then I removed .canto-ng, started it again, then killed canto-daemon, removed everything from "feeds"[] list in config, added plugin and started it again - everything worked (so far). So I guess the best solution for those folks who just wishes to plug in their inoreader configuration and have everything synced with canto would be to have clean "feeds"[] inside configuration file from the beginning (anyway, everyone has their own feeds).

**Comment by themoken** [comment]
Actually, I just pushed a sync-inoreader update that should keep it from trying to redefine feeds with the same name. Hopefully that should keep this error from happening again.

I'm closing this, because the colors / curses are unrelated to the real issue, but if you run into this daemon error again, then please open an issue against canto-next.
